name: ChestScreen
main: kloudy.mc.chestscreen.ChestDisplay
version: 1.1
author: Kloudy

commands:
  cd:
    description: used to define commands for the ChestDisplay plugin
    
permissions:
  cscreate:
    description: Allows a player to create a ChestScreen Display
    default: op